export { default as Home } from './Home'
export { default as Signup } from './Signup'
export { default as Signin } from './Signin'
export { default as NotFound } from './404'
export { default as Profile } from './Profile'
